aws_cli_path: /path/to/aws
s3_bucket: your-s3-bucket-name
replicate_api_key: your-replicate-api-key
replicate_api_url: https://api.replicate.com/v1/predictions
replicate_model_version: your-replicate-model-version
huggingface_token: your-huggingface-token
anthropic_api_key: your-anthropic-api-key
anthropic_api_url: https://api.anthropic.com/v1/messages
openai_api_key: your-openai-api-key
openai_api_url: https://api.openai.com/v1/audio/transcriptions   # for transcription
openai_chat_api_url: https://api.openai.com/v1/chat/completions     # for clip generation
transcription_model: replicate   # Options: replicate, openai
clip_generation_model: anthropic   # Options: anthropic, openai

